apiVersion: velero.io/v1
kind: Backup
metadata:
  name: patroni
  labels:
    velero.io/storage-location: default
  namespace: oadp-operator
spec:
  hooks: {}
  includedNamespaces:
    - patroni
  storageLocation: default
  ttl: 720h0m0s

